### PR TITLE
nunit.org url to https in nuspec

### PR DESCRIPTION
**Pull request by 304NotModified**
followup of [nunit/nunit#3160](https://github.com/nunit/nunit/pull/3160) ;)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Polite bump

**Comment by 304NotModified** [comment]
bump @ChrisMaddock

**Comment by ChrisMaddock** [comment]
@OsirisTerje - I see you've seen this PR, but not merged it. Any reason you were holding off, or can we pull it in? 😄

**Comment by OsirisTerje** [comment]
@ChrisMaddock  Thanks for the poke :-)   Merged now !

**Pull request merged**
