### PR TITLE
Add Dev14 support

### PR DESCRIPTION
**Pull request by SLaks**
Also remove incorrect copy local.

The solution should now build and install on VS 11, 12, and 14, and the build from any version should work on any other version.

### CODE REVIEW

**Comment by OsirisTerje** [comment]
I'll close this here, as the issue has been resolved.

**Comment by CharliePoole** [comment]
@OsirisTerje What issue is resolved? I can't find a reference. Also, is this closed because something is fixed? Because it's obsolete? etc.  Bookkeeping of issues is pretty boring, but we need to have it in order to track what's done and report it to people.

Also, have you reviewed this WRT the nunit3 adapter?

**Comment by OsirisTerje** [comment]
We do support Dev14,  aka VS2015, both for 2.6 and for V3.  I'll add Obsolete to it.

Sent from my Windows Phone
________________________________

**Comment by CharliePoole** [comment]
I see now that this PR was replaced by another PR, so the issue is more about that other PR #54. I really should have commented there.

**Pull request closed without merging**
