### PR TITLE
Update nunit reference to 2.7.1

### LINKED ISSUE #184: Update NUnit library to 2.7.1
It would be nice to update NUnit library to 2.7.1.

And also nicer to have a release :-) The first point we could do for you

### LINKED ISSUE #186: How to change used nunit 2 version of test adapter to e.g. v2.7.1 ?
How can I change the nunit 2 version of test adapter to e.g. v2.7.1 ?

### PR DESCRIPTION
**Pull request by BobSilent**
Updates the nunit reference to latest nunit2 binaries.
as existing binaries 2.6.4 do not support `OneTimeSetup` and `OneTimeTearDown`

having this in an official nunit-vs-adpater would help a lot in migrating from nunit2 to nunit3

resolves #184 
resolved #186

### CODE REVIEW

**Comment by CharliePoole** [comment]
Is it possible to switch to using the package rather than checking binaries into GitHub?

**Comment by BobSilent** [comment]
Sure, I will check it!
I just updated what was there, without bigger changes 😉 to make the release happen.
Because I need it for a larger set of nunit 2.4 Tests to migrate finally to nunit 3...

**Comment by BobSilent** [comment]
@CharliePoole is there a nuget package which contains these dlls
- nunit.core.dll
- nunit.core.interfaces.dll
- nunit.util.dll

I just found the TestRunner Package itself to contain them

**Comment by CharliePoole** [comment]
@BobSilent You found it while I slept! :smile:

**Comment by BobSilent** [comment]
But I did not find the util.dll, therefore this one is still checked in.

PackageReference is no big deal, but build needs to have a newer Visual Studio (currently 2015)

**Comment by CharliePoole** [comment]
I forgot about util. When I created the package for use by the v2 adapter extension, I managed to get rid of it by replicating a few helper classes. Probably not worth the trouble here, but that's up to @osiristerje as is the decision about which VA to target.

**Comment by BobSilent** [comment]
@CharliePoole @OsirisTerje how to proceed here?

**Comment by CharliePoole** [comment]
@BobSilent I got involved because I maintain the legacy NUnit V2 project and created the V2 pacakge. But I'm not on the team that works on the adapter any longer, so @OsirisTerje has to decide whether to merge your change. Since he hasn't commented here, I am wondering if he isn't getting notifications. I'll ping him with an email.

**Comment by OsirisTerje** [comment]
Sorry,  seems I lost the notifications for this some time ago.  Thanks @CharliePoole  for pinging me :-)

I'll have a look at this.

**Comment by BobSilent** [comment]
Thanks, it would really be helpful for me to get the latest binaries in here, it simplifies my migration path to v3.

And sorry for making stress 😀

**Comment by OsirisTerje** [comment]
Sorry,  seems I lost the notifications for this some time ago.  Thanks @CharliePoole  for pinging me :-)

I'll have a look at this.

**Comment by OsirisTerje** [comment]
Merged the PR now, there should be a new package out on the dev feed (myget) shortly.  I'll work through the stuff also and put out a quick beta probably tomorrow, that will then be on the nuget feed.

**Comment by BobSilent** [comment]
Thanks a lot.

**Pull request merged**
