### PR TITLE
Support Visual Studio vNext 15.0

### LINKED ISSUE #135: Support Visual Studio vNext 15.0

### PR DESCRIPTION
**Pull request by rprouse**
Upgrades the VSIX to the v3 VSIX format which is backwards compatible to VS 2012. Also incremented the version so we can release when ready.

Fixes #135

### CODE REVIEW

**Comment by CharliePoole** [comment]
I also discussed this by email. Summarizing:
1. It would help to have an issue for this so there is a place to explain to everyone why we are doing it.
2. There is no plan for a 2.2 release right now if we are going to do one, let's make a milestone.
3. This only partly advances us to 2.2, since it doesn't change anything but the vsix package version.

Up to now, we planned that 2.1 would be the final release of the (old) adapter. I can understand that there are some reasons to change that, but they are currently unstated reasons. Additionally, if we decide to have a 2.2 release, let's designate a release manager to do it and a date when we will release. 

I think our release plans are one of the few things we have to keep us all on the same track. Assuming all the thinking is done anyway - and I believe it is - it takes about 10 minutes to create a milestone that reflects the conclusions and shares the information with everyone.

**Comment by rprouse** [comment]
@CharliePoole you are correct, this should be reverted back to 2.1 and included in that release. It would be nice if we could get that release out soon to support VS vNext, but this PR isn't as time sensitive since we don't want to sim-ship this. I've created an issue and assigned it to 2.1

**Comment by rprouse** [comment]
@OsirisTerje and @CharliePoole any reason not to get this merged? I have reverted back to 2.1 as requested in the review.

**Comment by CharliePoole** [comment]
No reason... I think we just hadn't seen the commit.

**Pull request merged**
