### PR TITLE
Add Simpler Dev14 support

### PR DESCRIPTION
**Pull request by SLaks**
Also remove incorrect copy local.

The solution should now build and install on VS 11, 12, and 14, and the build from any version should work on any other version.

Microsoft.VisualStudio.TestPlatform.ObjectModel v11 must still exist on disk, as noted in the Wiki.

I believe that the unit tests will only work in VS2012, and that that was always true.

### CODE REVIEW

**Comment by CharliePoole** [comment]
@OsirisTerje This is an old one, so I'm just using it to explain something about how we need to track things. It's not really important to change this now, but if it were for a current release, here is what I would do.

If there is an issue that this fixes, add a 'fixes' comment so we can link to that issue. Presumably, that issue would tell someone what is being fixed. Give that issue appropriate labels, including closed:done. Assign a milestone and a person. Close the issue when this is merged.

Assuming there is not an issue, as often happens when a contributor does a pull, I would add a comment that says what this is fixing - my guess is there is nothing here because you guys corresponded offline about the problem. Treat the PR like an issue by giving it appropriate labels, a milestone and assigning the contributor. Handily enough, GitHub will list it in milestone reports along with actual issues and we will have a record of what was done in the milestone.

BTW, shouldn't the guy who did the PR be a contributor? Making someone a contributor allows us to assign issues to them and not much else, but it's handy for us and recognition for them.

I wrote something about all this process once, but I think it was in the mailing list. I should create something more permanent on the wiki.

**Comment by rprouse** [comment]
@OsirisTerje, if we start following the same procedures here as we do with NUnit, we can start auto-generating the release notes. After getting sick of manually creating the release notes for the last NUnit release, I sat down and started writing a program that will list all issues fixed for a given repository listed by the milestones they were completed in.

It is still a work in progress and likely won't fully automate the process, but it is a start :smile: https://github.com/rprouse/GetChanges

**Comment by OsirisTerje** [comment]
That sounds great !
I do believe we have it more or less the same.  Anything in particular you notice as different ?

**Comment by rprouse** [comment]
The big thing I see is that there are no release milestones and that closed issues are not assigned to a milestone so we cannot automatically categorize them and assign them to a release. It is also useful if all closed issues have a label applied as to why they were closed so that we can exclude questions, won't fix, invalid, etc issues from the release notes.

If you go into the main nunit repository and look at all the closed issues, you will be able to see exactly which release they were fixed in by looking at the milestone. Before we release, we look at all closed issues and make sure they all have the correct milestone applied. That is usually pretty easy since we only have to look at closed issues in future releases or without milestones since we never leave open issues in a released milestone.

**Comment by CharliePoole** [comment]
It sure does sound great!

But even though we are basically geeks, I hope "We can all work together
more easily" is a good reason as well. :-)

Main diffs I see WRT producing the release notes.

* Not always having issues or issue-equivalent (PRs with a milestone and
labels)
* Sometimes having both the PR and the issue in the milestone, which would
cause double listing.
* Not marking closed:done versus other types of close.


Let's push this from both ends. That is, I'll update the docs on how we
handle issues manually while Rob finishes up his get changes utility and we
try it out to find what holes we have in the process.

Charlie

**Comment by CharliePoole** [comment]
Maybe it will help if I describe what I do to create release notes when I do a release. Note that the GitHub display for milestones includes both issues and PRs. I'll use 'items' here.

1. Look at all **future** milestones to see if any have completed items. This happens when we work ahead of the planned milestone but forget to change the milestone. I move these to the current milestone, since that's actually when they are being released.

2. Look at all closed items in the milestone I'm releasing. If some items are PRs I check to see if there is a corresponding issue. If so, I any labels from the PR and take it out of the milestone so we don't have duplication.

3. Continuing to look a the closed items, I make sure each one has an is: label and a closed:label. If not I apply one, removing any status: labels as well. The is: label is useful in future queries. The closed; label is too and is also used in the rest of this procedure.

3. Now that everything has a closed: label, I remove those that are not closed:done from the milestone. We don't list things we decided not to do or issues that were invalid in the release notes.

4. The milestone display now contains a list of issues for the release notes. At times, I just retype it and at others I have done a copy/paste after sorting the list in the correct order. In the case of NUnit, we have a CHANGES.txt file as well as the release notes in the wiki. I generally create the text file first and then use it to create the release notes. This is easier now than in the past, since I don't have to use html. The text file is almost but not quite markdown.

Feel free to suggest changes to this process. The use of labels is a bit burdensome, but it's what we took on when we opted for the convenience of using GitHubs issue system.

@rprouse Maybe some of the cleanup I do can also be automated.

**Comment by CharliePoole** [comment]
@rprouse ... or if not automated, maybe a problem report that tells us what needs changing.

**Comment by OsirisTerje** [comment]
The 5 points list above should be in the wiki. This is great process documentation.  
This wiki - not sure which ones is best, we should have one at the org level, but I guess that is not possible.  
I also seem to remember you wrote down something about the labels earlier, but right now I can't find that info.  This should be in the same place.

**Comment by CharliePoole** [comment]
I had the same memory, but it's not in the process documentation, which is on the dev wiki.

We created the dev wiki as a substitute for an org level wiki. The documentation for release of NUnit and for release of the NUnit3 adapter are both there under tech notes.

**Comment by OsirisTerje** [comment]
FYI:  I have earlier documented the release process for the adapter here:  https://github.com/nunit/nunit-vs-adapter/wiki/How-to-build-and-package-a-release

**Comment by CharliePoole** [comment]
In fact, I started with a copy of that when I wrote the docs for the nunit3 adapter.

**Pull request merged**
